### ISSUE TITLE
Could not initialize hg_class

### ISSUE THREAD

**Issue by ctminh** [scs-lab/hcl#1]
Hi,
I tried to play around with HCL on our system (including 2 nodes over MQM8790-Mellanox Quantum™ 40-port Non-blocking Externally Managed HDR 200Gb/s). But it sounds "could not init the margo services" with the following errors:
_# [1450118.071964] mercury->fatal: [error] /tmp/ra56kop/spack-stage/spack-stage-mercury-2.0.1rc3-565ptkns6xy2w6ngya2ylvpdjow5blhp/spack-src/src/na/na.c:321_
_# NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://rome2:9000
[error] Could not initialize hg_class..._
Could that be because of new versions (mercury, thallium that I used)? Do you have any recommendations for this?

Another point is: I have tried "compiling mercury-1.0.1 with the patch in hcl-src". However, it seems to be a problem with libfabric (the available version on our system is 1.10.0, the older ones could not work).
_../../bin/libmercury_util.so.1.0.1 /home/ra56kop/loc-libs/spack/opt/spack/linux-sles15-zen2/gcc-10.2.1/libfabric-1.10.0-4ucnv26kqcplfnkxeedw3mb4ywyinkn3/lib/libfabric.so -lpthread -lrt
158    /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/na.dir/na_ofi.c.o:/tmp/ra56kop/spack-stage/spack-stage-mercury-1.0.1-jd3i45iu
         7m3bnlyu6b262fhu34ducabg/spack-src/src/na/na_plugin.h:119: multiple definition of `na_ofi_class_ops_g'; CMakeFiles/na.dir/na.c.o:/tmp/ra56kop/spack-stage/spack-stage-mercury-1.0.1-jd3i45iu7m3bnlyu6b262fhu34ducabg/spack-src/src/na/na_plugin.h:119: first defined here
..._
Do you have any suggestions?
Thanks!

**Comment by hariharan-devarajan** [comment]
> Hi,
> I tried to play around with HCL on our system (including 2 nodes over MQM8790-Mellanox Quantum™ 40-port Non-blocking Externally Managed HDR 200Gb/s). But it sounds "could not init the margo services" with the following errors:
> _# [1450118.071964] mercury->fatal: [error] /tmp/ra56kop/spack-stage/spack-stage-mercury-2.0.1rc3-565ptkns6xy2w6ngya2ylvpdjow5blhp/spack-src/src/na/na.c:321_
> _# NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://rome2:9000 [error] Could not initialize hg_class..._
> Could that be because of new versions (mercury, thallium that I used)? Do you have any recommendations for this?

The error seem like your domain lookup is failing.
Some debugging points:
- Could you Try ofi+sockets version? Just for testing purposes. 
- try IP of the IB card instead of hostname. Sometimes the hostname lookup failed.
- Output of fi_info
- Domain name is just an OFI "thing" that allows selection of the right device to use, it just happens that when using the verbs transport, the domain name matches the IB device name (what you get from the ibv_devices command) and not the interface name since again, you would not necessarily have IPoIB configured. In the case of sockets though, the domain name should not be the same, the domain name is the interface name since you do need IPs in that case, so OFI uses the interface name, i.e. ib1 if you configured IPoIB.
- I know your following the documentation. But can you instead use this format. ofi+verbs://mlx5_0/ib1:12345. They seem to have changed it recently.

**Comment by hariharan-devarajan** [comment]
> Another point is: I have tried "compiling mercury-1.0.1 with the patch in hcl-src". However, it seems to be a problem with libfabric (the available version on our system is 1.10.0, the older ones could not work).
> _../../bin/libmercury_util.so.1.0.1 /home/ra56kop/loc-libs/spack/opt/spack/linux-sles15-zen2/gcc-10.2.1/libfabric-1.10.0-4ucnv26kqcplfnkxeedw3mb4ywyinkn3/lib/libfabric.so -lpthread -lrt 158 /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/na.dir/na_ofi.c.o:/tmp/ra56kop/spack-stage/spack-stage-mercury-1.0.1-jd3i45iu 7m3bnlyu6b262fhu34ducabg/spack-src/src/na/na_plugin.h:119: multiple definition of `na_ofi_class_ops_g'; CMakeFiles/na.dir/na.c.o:/tmp/ra56kop/spack-stage/spack-stage-mercury-1.0.1-jd3i45iu7m3bnlyu6b262fhu34ducabg/spack-src/src/na/na_plugin.h:119: first defined here ..._
> Do you have any suggestions?
> Thanks!

This was for RoCE and it was fixed in newer versions of mercury.

**Comment by hariharan-devarajan** [comment]
If I can get access, I would be happy to help debug and get you started with HCL.

**Comment by ctminh** [comment]
Hi @hariharan-devarajan, thank you!
**1. Could you Try ofi+sockets version? Just for testing purposes.**: Yes, I tried this, it was fine with ofi+sockets. Some results (from the queue_test example), i.e.,
_... local_queue_throughput get: 59.221793, remote queue throughput (put): 69.806545 ..._
**2. try IP of the IB card instead of hostname. Sometimes the hostname lookup failed.**: Ah, as you mentioned I also tried this one, but nothing changes as follow,
_# [8243.575431] mercury->fatal: [error] /tmp/ra56kop/spack-stage/spack-stage-mercury-2.0.1rc3-frvg6o6qaeladue6apdrlr2ennnfgd3x/spack-src/src/na/na.c:321_
_# NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://10.12.1.2:9000
[error] Could not initialize hg_class_
**3. Output of fi_info**: it looks like this, e.g.
_provider: verbs;ofi_rxm
    fabric: IB-0xfe80000000000000
    domain: mlx5_0
    version: 111.10
    type: FI_EP_RDM
    protocol: FI_PROTO_RXM
..._
And, what I get from the ibv_devices command: I think both nodes are fine with ib_devices.
    _device          	   node GUID
    ------          	----------------
    mlx5_0          	1c34da03004e77fc_
**4. If I can get access, I would be happy to help debug and get you started with HCL.**
I am not sure I can grant you access, because I don't have that permission. But maybe if you have time, I could share you my screen over video call and something like that, you can control over there. But not 100% sure it would work for you :).

**Comment by hariharan-devarajan** [comment]
Hi @ctminh 

I saw this thread, [#297](https://github.com/mercury-hpc/mercury/issues/297). Here they recommend to use this format 
```
ofi+verbs://mlx5_0/rome2:12345
```

Also, you have to debug the mercury code at mercury/src/na/na_ofi.c:1672. Through that we can find what format mercury needs to run with your machine.

**Comment by ctminh** [comment]
Hi, ok let me check that thread #297. But I also tried "running mochi-thallium alone with verbs". It was fine on our testbed machine. For example:
_mpirun -n 2 -ppn 1 --host rome1,rome2 ./tl_string_rdma_transf
[R1] is initializing the tl-client...
[R0] is initializing the tl-server at rome1
[R0] inits tl-server at ofi+verbs;ofi_rxm://10.12.1.1:57681
[R0] casts the addr to string-type: ofi+verbs;ofi_rxm://10.12.1.1:57681
[R1] got the serv-addr: ofi+verbs;ofi_rxm://10.12.1.1:57681
..._

**Comment by hariharan-devarajan** [comment]
> Hi, ok let me check that thread #297. But I also tried "running mochi-thallium alone with verbs". It was fine on our testbed machine. For example:
> _mpirun -n 2 -ppn 1 --host rome1,rome2 ./tl_string_rdma_transf [R1] is initializing the tl-client... [R0] is initializing the tl-server at rome1 [R0] inits tl-server at ofi+verbs;ofi_rxm://10.12.1.1:57681 [R0] casts the addr to string-type: ofi+verbs;ofi_rxm://10.12.1.1:57681 [R1] got the serv-addr: ofi+verbs;ofi_rxm://10.12.1.1:57681 ..._

Can you send me your sample test. As I remember the examples from the repo, they do not pass hostnames. If you change the test to use hostnames or IPs then the lookup fails. That's the cause. It has confused me as well multiple times.

Also, I have had this issue with a different version of mercury on 1.0.1. What I did was debug at 
https://github.com/mercury-hpc/mercury/blob/v2.0.1rc3/src/na/na.c#L247. Here you should be able to see what part of the string it doesn't work with.

FYI, this is the only (thought biggest) hurdle you will ever have with mercury.

**Comment by ctminh** [comment]
Hi, yes my test with thallium alone, https://github.com/ctminh/task-based-models-survey/blob/master/others/thallium/tl_string_transf_mpi_omp/tl_string_rdma_transf.cpp. I tried to create 2 mpi-ranks, 1 per node, then create a random string and transfer it via thallium-rpc over rdma.

**Comment by hariharan-devarajan** [comment]
> Hi, yes my test with thallium alone, https://github.com/ctminh/task-based-models-survey/blob/master/others/thallium/tl_string_transf_mpi_omp/tl_string_rdma_transf.cpp. I tried to create 2 mpi-ranks, 1 per node, then create a random string and transfer it via thallium-rpc over rdma.

If check this line, https://github.com/ctminh/task-based-models-survey/blob/master/others/thallium/tl_string_transf_mpi_omp/tl_string_rdma_transf.cpp#L87.

The lookup doesn't happen on the server which in HCL's case happens as we pass the hostname

If you modify the constructor to use the URI ofi+verbs;ofi_rxm://10.12.1.1:57681. You would see the error. As it would now go through the method I mentioned in the previous comment.

**Comment by ctminh** [comment]
So, what should I do as a quick change now? Should I change the string (e.g., VERBS_CONF, ...) in configuration_manager.h of hcl-src?
As your previous comments, I also changed the queue_test.cpp here (https://github.com/ctminh/task-based-models-survey/tree/master/others/hcl_examples/queue_test, the same one in the test-folder of hcl), instead of using hostname, I used IP of IB-card. But it didn't work as well: _# NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://10.12.1.2:9000_
Anyway, I'm checking the thread you mentioned [https://github.com/mercury-hpc/mercury/issues/297](url).

**Comment by hariharan-devarajan** [comment]
> So, what should I do as a quick change now? Should I change the string (e.g., VERBS_CONF, ...) in configuration_manager.h of hcl-src?
> As your previous comments, I also changed the queue_test.cpp here (https://github.com/ctminh/task-based-models-survey/tree/master/others/hcl_examples/queue_test, the same one in the test-folder of hcl), instead of using hostname, I used IP of IB-card. But it didn't work as well: _# NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://10.12.1.2:9000_
> Anyway, I'm checking the thread you mentioned [https://github.com/mercury-hpc/mercury/issues/297](url).

I meant in your test of Thallium only case, Change the example at line 87 to
```
tl::engine ser_engine("ofi+verbs;ofi_rxm://10.12.1.1:57681", THALLIUM_SERVER_MODE);
```
And run it to see if the call is successful.

Once we get that running, we can modify HCL to match that.

Sounds good?

**Comment by ctminh** [comment]
Hi, it works. I have changed (my thallium-only test):
```
// init the tl-server mode
tl::engine ser_engine("ofi+verbs;ofi_rxm://10.12.1.1:52664", THALLIUM_SERVER_MODE);
```
Then run it, it works:
```
[R0] inits tl-server at ofi+verbs;ofi_rxm://10.12.1.1:52664
...
[R1] got the serv-addr: ofi+verbs;ofi_rxm://10.12.1.1:52664
```

**Comment by hariharan-devarajan** [comment]
> Hi, it works. I have changed (my thallium-only test):
> 
> ```
> // init the tl-server mode
> tl::engine ser_engine("ofi+verbs;ofi_rxm://10.12.1.1:52664", THALLIUM_SERVER_MODE);
> ```
> 
> Then run it, it works:
> 
> ```
> [R0] inits tl-server at ofi+verbs;ofi_rxm://10.12.1.1:52664
> ...
> [R1] got the serv-addr: ofi+verbs;ofi_rxm://10.12.1.1:52664
> ```

Ok what about. ofi-verbs;mlx5_0://10.12.1.2:9000

**Comment by ctminh** [comment]
Hi, now it doesn't work, get back to the error at the beginning :)
```
[R0] is initializing the tl-server at rome1
# [84385.327978] mercury->fatal: [error] /tmp/ra56kop/spack-stage/spack-stage-mercury-2.0.1rc3-565ptkns6xy2w6ngya2ylvpdjow5blhp/spack-src/src/na/na.c:321
# NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://10.12.1.1:9000
[error] Could not initialize hg_class
```

**Comment by hariharan-devarajan** [comment]
> Hi, now it doesn't work, get back to the error at the beginning :)
> 
> ```
> [R0] is initializing the tl-server at rome1
> # [84385.327978] mercury->fatal: [error] /tmp/ra56kop/spack-stage/spack-stage-mercury-2.0.1rc3-565ptkns6xy2w6ngya2ylvpdjow5blhp/spack-src/src/na/na.c:321
> # NA_Initialize_opt(): No suitable plugin found that matches ofi-verbs;mlx5_0://10.12.1.1:9000
> [error] Could not initialize hg_class
> ```

Perfect. I expected it to fail.
Now switch the string to ofi-verbs;ofi_rxm://10.12.1.2:9000. And it would work. If it does then,

So you need to use your domain in HCL as ofi_rxm
https://github.com/scs-lab/hcl/blob/master/include/hcl/common/configuration_manager.h#L62

**Comment by ctminh** [comment]
Hi, it's a bit sensitive :). **ofi+verbs**;ofi_rxm://10.12.1.1:9000 works, but **ofi-verbs** could not work. Anyway, I will try to change the domain, and run hcl-example again.

**Comment by hariharan-devarajan** [comment]
> **+verbs**;ofi_rxm://10.12

Make sure, you get the same string on HCL which works :).

**Comment by ctminh** [comment]
Hi, it works now, I have changed in https://github.com/scs-lab/hcl/blob/master/include/hcl/common/configuration_manager.h#L62: _TCP_CONF("ofi+sockets"), VERBS_CONF("ofi+verbs"), VERBS_DOMAIN("ofi_rxm"),_
Then, run it, and the results of the queue_test example (on 2 nodes, 4 ranks in total, 2 ranks/node), e.g.,:
```
llocal_queue_throughput put: 33047.800338
llocal_queue_throughput get: 46020.852969
local_queue_throughput put: 15.790689
local_queue_throughput get: 183.191856
remote queue throughput (put): 149.194455
remote queue throughput (get): 164.833654
```
Just wondering it looks not so much faster than the mode of ofi+sockets as I mentioned before, right?
_**Yes, I tried this, it was fine with ofi+sockets. Some results (from the queue_test example), i.e.,**_
`... local_queue_throughput get: 59.221793, remote queue throughput (put): 69.806545 ...`
How do you think?

**Comment by hariharan-devarajan** [comment]
> Hi, it works now, I have changed in https://github.com/scs-lab/hcl/blob/master/include/hcl/common/configuration_manager.h#L62: _TCP_CONF("ofi+sockets"), VERBS_CONF("ofi+verbs"), VERBS_DOMAIN("ofi_rxm"),_
> Then, run it, and the results of the queue_test example (on 2 nodes, 4 ranks in total, 2 ranks/node), e.g.,:
> 
> ```
> llocal_queue_throughput put: 33047.800338
> llocal_queue_throughput get: 46020.852969
> local_queue_throughput put: 15.790689
> local_queue_throughput get: 183.191856
> remote queue throughput (put): 149.194455
> remote queue throughput (get): 164.833654
> ```
> 
> Just wondering it looks not so much faster than the mode of ofi+sockets as I mentioned before, right?
> _**Yes, I tried this, it was fine with ofi+sockets. Some results (from the queue_test example), i.e.,**_
> `... local_queue_throughput get: 59.221793, remote queue throughput (put): 69.806545 ...`
> How do you think?

The performance depends on two things.
1. For small elements (< 32KB in experimentation) you will have similar performance for TCP and IB. As you increase request sizes (i.e. data structure size, IB is way better because of better bandwidth saturation)
2. You need to check the concurrency of the queue. In my experience, you need multiple clients (or processes) over a single server to saturate the network. 


Hence, if in your application, you plan to have data structures with small elements (both ofi+sockets and verbs would perform similar until you saturate the network of TCP through concurrency and past that verbs will keep on increasing based on your bandwidth of IB.

Does that make sense?

If you want to extract maximum performance. Then spawn another issue, describing use case I can suggest some deployment models for better performance.

**Comment by ctminh** [comment]
Hi, great! I think so.
Let me open another issue then.
Thank you very much, @hariharan-devarajan!
I think we could close this issue for now.
